### ISSUE TITLE
Тест на html/css

### ISSUE THREAD

**Issue by yurkorudi** [yurkorudi/ChaplinWeb#2]
Коротше Пауло... Там є папка тест, в ній є все що потрібно для хоум пейдж на даний момент, я не можу розібратись що не так з картинками, вони тупо не завантажуюються, і це дуже дуже зле... Глянь буласка до цього, якщо матимеш якісь ідеї для вирішення то зроби то і скажеш, бо я поки що без варіантів, пробував по різному, ніяк не йде

**Comment by PaulStefanyshyn** [comment]
Всі елементи підвантажуються, просто варто змінити стилі

**Comment by PaulStefanyshyn** [comment]
<link rel="stylesheet" href="/static/css/styles.css">
Була відсутня логіка для зв'язку файлу стилів та html сторінки
