### ISSUE TITLE
РЕКТАНГЛ В ОБ'ЄКТ (забрати картинку..)

### ISSUE THREAD

**Issue by yurkorudi** [yurkorudi/ChaplinWeb#3]
Коротше... Треба замість картинки ректангл вставити такий самий ректангл просто об'єктом, в ньому ве зробити лінійний градієнт і т.д., бо картинка то в нас не буде розтягуватись відповідно до зміни дісплею, а треба щоб розтгувалось. Попробував то зробити, але воно мене замухало, не вдалось.. Просто тоді всі об'єкти не нахожять на нього не зважаючи на оверлей... 
Ось, та й таке

**Comment by PaulStefanyshyn** [comment]
А якщо просто залити головний блок градієнтом як backgroun-color? Думаю там вийде налаштувати коефіцієнт кількості червоного + напрям зміни градієнтув

**Comment by yurkorudi** [comment]
ну то файно, по факту справились, закриважмо прилавку
